### PR TITLE
official_devices: Fix Stale JSON

### PR DESCRIPTION
**Pull request by twistloop**
* Fixes download site crash

### CODE REVIEW

**Comment by Abhinavgupta371** [comment]
@twistloop pro re bhai bhai bhai

**Comment by twistloop** [comment]
@twistloop @FireLord1 please merge

**Comment by FireLord** [comment]
@twistloop Wtf underground , underfucker professionalism guru 

The real PRO

**Comment by EnesSastim** [comment]
@twistloop Lmao

**Comment by FireLord** [comment]
@twistloop First I apply Vicks then I close your git

**Comment by ishubhamsingh** [comment]
@twistloop gerrit re

**Comment by twistloop** [comment]
k pro @ishubhamsingh sir

**Comment by Abhinavgupta371** [comment]
@ishubhamsingh bc merge kro xD

**Comment by darshan1205** [comment]
@Abhinavgupta371 Gerrit only

**Pull request closed without merging**
