### PR TITLE
add oneplus3 pie

### PR DESCRIPTION
**Pull request by GeorgeYuan233**

### CODE REVIEW

**Comment by Abhinavgupta371** [comment]
@GeorgeYuan233 gerrittttttt

**Comment by GeorgeYuan233** [comment]
@Abhinavgupta371 OK，I will.Can u give me link to where should I push it

**Comment by SakilMondal** [comment]
@GeorgeYuan233 Read properly

https://github.com/AospExtended/Documentation_and_thread-template

**Comment by GeorgeYuan233** [comment]
@sakindia123 I have finished it, then what should I do?

**Comment by SakilMondal** [comment]
@GeorgeYuan233 Push your changes to Gerrit 🙄

**Comment by GeorgeYuan233** [comment]
@sakindia123 OK

**Comment by GeorgeYuan233** [comment]
@sakindia123 OK，I will

**Pull request closed without merging**
