### PR TITLE
device: Add jasmine

### PR DESCRIPTION
**Pull request by TingyiChen**
Signed-off-by: Isaac Chen <isaacchen@isaacchen.cn>

### CODE REVIEW

**Comment by twistloop** [comment]
@TingyiChen thug af

**Comment by razorrahul123** [comment]
@TingyiChen For iPhone SE when?

**Comment by TingyiChen** [comment]
@razorrahul123 Give LINUX SRC FIRST

**Comment by TingyiChen** [comment]
@TingyiChen Someone pls merge this

**Comment by EnesSastim** [comment]
@TingyiChen PRO ASFAK

**Comment by Abhinavgupta371** [comment]
@TingyiChen Peru sur

**Pull request merged**
