### PR TITLE
official devices: Add support for Z010D

### PR DESCRIPTION
**Pull request by SakilMondal**
What's working:
- Everything except bugs mentioned below

Bugs:
- VoLTE calls
-Have some issues with stock cam video recording (footej, GCam works)
-SELinux is permissive

### CODE REVIEW

**Comment by theimpulson** [comment]
@SakilMondal 👀

**Comment by SakilMondal** [comment]
😇

**Comment by thejustech** [comment]
@SakilMondal @darshan1205

**Comment by SakilMondal** [comment]
> @SakilMondal @darshan1205

What ? 😒

**Comment by thejustech** [comment]
@SakilMondal Commented by Github BOT on my behalf by Mistake.

**Comment by darshan1205** [comment]
@thejustech Push on gerrit.aospextended.com

**Comment by allstargaurav** [comment]
Read this https://github.com/AospExtended/Documentation_and_thread-template 
And fill the Google form also push this via our gerrit
Closing this pull request

**Pull request closed without merging**
