### PR TITLE
Add xiaomi Poco F1

### PR DESCRIPTION
**Pull request by shahan-mik3**

### CODE REVIEW

**Comment by sb6596** [comment]
@shahan-mik3 Beryllium

**Comment by sb6596** [comment]
@shahan-mik3 👈 Build bot? 🤔

**Comment by shahan-mik3** [comment]
wew thanks muster

**Comment by EnesSastim** [comment]
@shahan-mik3 XD dont fight sar

**Comment by twistloop** [comment]
Woah!

**Comment by EnesSastim** [comment]
OwO

**Comment by Abhinavgupta371** [comment]
@EnesSastim

**Comment by EnesSastim** [comment]
@Abhinavgupta371 what

**Pull request merged**
