### PR TITLE
Update devices.json

### PR DESCRIPTION
**Pull request by jorgelucasd00**
Add Sanders

### CODE REVIEW

**Comment by sb6596** [comment]
@jorgelucasd00 Gerrit please

**Comment by jorgelucasd00** [comment]
! [remote rejected] HEAD -> refs/for/main (change http://gerrit.aospextended.com/c/AospExtended/official_devices/+/348 closed)
error: failed to push some refs to 'ssh://jorgelucasd00@gerrit.aospextended.com:29418/AospExtended/official_devices'

**Comment by jorgelucasd00** [comment]
@sb6596 ! [remote rejected] HEAD -> refs/for/main (change http://gerrit.aospextended.com/c/AospExtended/official_devices/+/348 closed)
error: failed to push some refs to 'ssh://jorgelucasd00@gerrit.aospextended.com:29418/AospExtended/official_devices'

**Comment by jorgelucasd00** [comment]
@sb6596 help me please

**Comment by sb6596** [comment]
@jorgelucasd00 Force sync this repo OR delete old repo and clone new one. You fucked up this one 😐

**Pull request closed without merging**
